spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:44658/railway
spring.datasource.username=root
spring.datasource.password=UXAfbLfOiXNyWYksRIilrvLqzLOpHsvM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port = 8080
server.address=0.0.0.0